name: Flutter Web Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Build web app
        working-directory: children_games/
        run: flutter build web --release --base-href /children-games/
      - name: Configure Git, commit, and push
        working-directory: children_games/
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
